name: steps output
on: workflow_dispatch

jobs: 
  job1: 
    outputs:
      data_from_job1: 
        job1_name = ${{steps.set-output.outputs.name}}
      
    runs-on: ubuntu-latest
    steps: 
      - name: first step
        id: set-output
        shell: bash
        run: |
          echo "name=Puhan" >> $GITHUB_OUTPUT
          echo "age=23" >> $GITHUB_OUTPUT
      - name: print output 
        run: |
          echo "My name is ${{steps.set-output.outputs.name}}"
          echo "My age is ${{steps.set-output.outputs.age}}"
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: get data from job1 
        run: 
          echo "i am coming from job1 ${{ needs.job1.outputs.data_from_job1}}"
      
    
      
