name: steps output
on: workflow_dispatch

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - name: first step
        id: set-output
        shell: bash
        run: |
          echo "name=Puhan" >> $GITHUB_OUTPUT
          echo "age=23" >> $GITHUB_OUTPUT
      - name: print output 
        run: |
          echo "My name is ${{steps.set-output.outputs.name}}"
          echo "My age is ${{steps.set-output.outputs.age}}"
      
          
      
